# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

decimal_add <- function(a1, a2) {
    .Call(`_decimal_decimal_add`, a1, a2)
}

decimal_minus <- function(a1, a2) {
    .Call(`_decimal_decimal_minus`, a1, a2)
}

decimal_multiply <- function(a1, a2) {
    .Call(`_decimal_decimal_multiply`, a1, a2)
}

decimal_divide <- function(a1, a2) {
    .Call(`_decimal_decimal_divide`, a1, a2)
}

decimal_equal <- function(a1, a2) {
    .Call(`_decimal_decimal_equal`, a1, a2)
}

decimal_notequal <- function(a1, a2) {
    .Call(`_decimal_decimal_notequal`, a1, a2)
}

decimal_lessequal <- function(a1, a2) {
    .Call(`_decimal_decimal_lessequal`, a1, a2)
}

decimal_greaterequal <- function(a1, a2) {
    .Call(`_decimal_decimal_greaterequal`, a1, a2)
}

decimal_greater <- function(a1, a2) {
    .Call(`_decimal_decimal_greater`, a1, a2)
}

decimal_less <- function(a1, a2) {
    .Call(`_decimal_decimal_less`, a1, a2)
}

